# Generated by Django 2.0.2 on 2018-03-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('playerID', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('buyingPrice', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isUniversal', models.BooleanField()),
                ('numPlayers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyingPower', models.DecimalField(decimal_places=2, max_digits=25)),
                ('percentChange', models.DecimalField(decimal_places=2, max_digits=25)),
                ('totalWorth', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('startingBalance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('adminID', models.IntegerField()),
                ('isCrypto', models.BooleanField()),
                ('joinPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('ticker', models.CharField(max_length=5)),
                ('shares', models.IntegerField()),
                ('isBuy', models.BooleanField()),
                ('leagueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.League')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('leagueID0', models.IntegerField()),
                ('leagueID1', models.IntegerField()),
                ('leagueID2', models.IntegerField()),
                ('leagueID3', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player10', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player11', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player12', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player13', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player14', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID15',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player15', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID16',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player16', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID17',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player17', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID18',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player18', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID19',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player19', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID20',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player20', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='playerID9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player9', to='home.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='settingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Setting'),
        ),
        migrations.AddField(
            model_name='asset',
            name='leagueID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.League'),
        ),
    ]
