# Generated by Django 2.0.2 on 2018-03-26 14:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('playerID', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('buyingPrice', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isUniversal', models.BooleanField()),
                ('numPlayers', models.IntegerField()),
                ('beginDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('endDate', models.DateTimeField()),
                ('startingBalance', models.DecimalField(decimal_places=2, max_digits=40)),
                ('adminID', models.IntegerField()),
                ('isCrypto', models.BooleanField()),
                ('joinPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyingPower', models.DecimalField(decimal_places=2, max_digits=25)),
                ('percentChange', models.DecimalField(decimal_places=2, max_digits=25)),
                ('totalWorth', models.DecimalField(decimal_places=2, max_digits=25)),
                ('leagueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.League')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('ticker', models.CharField(max_length=5)),
                ('shares', models.IntegerField()),
                ('isBuy', models.BooleanField()),
                ('leagueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.League')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='leagueID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.League'),
        ),
    ]
