# Generated by Django 2.0.2 on 2018-03-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180324_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='playerID10',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player10', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID11',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player11', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID12',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player12', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID13',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player13', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID14',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player14', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID15',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player15', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID16',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player16', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID17',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player17', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID18',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player18', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID19',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player19', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID20',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player20', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID6',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID7',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID8',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='home.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='playerID9',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player9', to='home.Player'),
        ),
    ]
