# Generated by Django 2.0.2 on 2018-04-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180417_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cumWorth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='isAi',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
