# Generated by Django 2.0.2 on 2018-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180427_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='TitanCoins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
