# Generated by Django 2.0.2 on 2018-04-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_titancoins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='TitanCoins',
            new_name='titanCoins',
        ),
    ]
