# Generated by Django 2.0.2 on 2018-04-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180427_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='titanCoins',
            new_name='TitanCoins',
        ),
    ]
