# Generated by Django 2.0.2 on 2018-04-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180427_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='hasEnded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
