# Generated by Django 2.0.3 on 2018-04-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_league_isai'),
        ('home', '0006_auto_20180427_1548'),
    ]

    operations = [
    ]
