# Generated by Django 2.0.2 on 2018-04-29 02:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_league_hasended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='TitanCoins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statement',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trophies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=8),
        ),
    ]
