# Generated by Django 2.0.2 on 2018-04-29 04:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180429_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trophies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[0, 0, 0, 0, 0, 0, 0, 0], size=8),
        ),
    ]
